# Permalinks
#
permalink:           pretty

# Setup
title:               Talita Sara
tagline:             'a menina mais linda do mundo'
description:         'Precisa de uma descrição'
url:                 http://talitasara.github.io
baseurl:             ''
paginate:            5
paginate_path:       "page:num"
gems:                [jekyll-paginate]

# About/contact
author:
  name:              OmeGa
  url:               https://github.com/alpha-omega
#  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
